# ----------------------------------------------------------------
# 分析設定
# ----------------------------------------------------------------
analysis_target_count: 1000        # Twitchから取得・分析するゲームの件数
notification_score_threshold: 10  # このスコアを超えたゲームだけを通知する
# ----------------------------------------------------------------
# あなたのチャンネル情報（競合分析に利用）
# ----------------------------------------------------------------
channel_profile:
  avg_viewers: 10  # ★★★あなたの配信の平均視聴者数をここに記入★★★

# ----------------------------------------------------------------
# あなたの配信スケジュール（配信時間との一致度評価に利用）
# ----------------------------------------------------------------
stream_slots:            
  mon: ["24-27"]  # ★★★あなたの配信スケジュールに合わせて書き換える★★★
  tue: ["24-27"]
  wed: ["24-27"]
  thu: ["24-27"]
  fri: ["24-27"]
  sat: ["24-27"]
  sun: ["24-27"]

# (以下、weights, penaltiesセクションは基本的にこのままでOK)
weights:
  viewers_per_ch: 0.5
  drops: 10
  free: 15
  steam_ccu_ratio: 10
  trends_jp_spike: 15
  twitter_jp_spike: 20
  slot_fit: 20
  blue_ocean_bonus: 25
  upcoming_event_score: 20 # 未来のイベントのスコアを50倍して最終スコアに加算する
  drops: 20                  # Twitch Dropsが有効な場合の加点
  steam_news_update: 15      # Steamニュースにアプデ情報があった場合の加点
  

penalties:
  top_share:    {threshold: 0.7, weight: 40}
  competitor_penalty: {threshold: 20, weight: 15}
  low_jp_ratio: {threshold: 0.05, weight: 25} # 日本語配信が5%未満なら、25点減点

notify:
  webhooks:
    radar_3d:  ${DISCORD_WEBHOOK_URL_3D}
    radar_7d:  ${DISCORD_WEBHOOK_URL_7D}
    radar_30d: ${DISCORD_WEBHOOK_URL_30D}
    
logging:
  sheet_id: "1btqoOdZA3pi1yGijPwBdlXwMHywaKI_Mz_3-n5vFbfE"