# 【最終版テンプレート】この内容を radar.yml に貼り付けてください

name: Hot-Games-Radar-PRO

on:
  workflow_dispatch: # 手動ボタンでいつでも起動
  schedule:
    - cron: "0 0,6,12 * * *" # 毎時15分と45分に自動実行 (UTC)

jobs:
  radar:
    runs-on: ubuntu-latest
    
    # ここで、GitHub Secretsに保管した全ての「鍵」をBotに渡します
    env:
      TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
      TWITCH_CLIENT_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET }}
      STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
      X_BEARER: ${{ secrets.X_BEARER }}
      DISCORD_WEBHOOK_URL_3D: ${{ secrets.DISCORD_WEBHOOK_URL_3D }}
      DISCORD_WEBHOOK_URL_7D: ${{ secrets.DISCORD_WEBHOOK_URL_7D }}
      DISCORD_WEBHOOK_URL_30D: ${{ secrets.DISCORD_WEBHOOK_URL_30D }}
      GCP_JSON: ${{ secrets.GCP_JSON }}
      
    steps:
      # 1. リポジトリのコードを仮想マシンにコピー
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Python環境をセットアップ
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip' # 依存関係をキャッシュして高速化

      # 3. 必要なPythonライブラリをインストール
      - name: Install dependencies
        run: pip install -r requirements.txt

      # 4. Botのメインプログラムを実行
      # (run.py や main.py という名前にしていることを想定)
      - name: Run Radar Bot
        run: python run.py # または python main.py